In [25]:
# import dependencies
import pandas as pd
import numpy as np

# create the dataframe
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
'Budapest_PaRis', 'Brussels_londOn'],
'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
'12. Air France', '"Swiss Air"']})

# Question 1
# replacing NAN values with the preceding values + 10 in FlightNumber Column
for i in range(df.FlightNumber.count() + 1):
    print(df.FlightNumber.loc[i,])
    if pd.isnull(df.FlightNumber.loc[i,]):
        df.loc[i,'FlightNumber'] = df.FlightNumber.loc[i-1,] + 10
        print(df.FlightNumber.loc[i,])

# Question 2 Separation of From_To columns into From and To
df_tmp = df.copy()
df_tmp[['From','To']] = df_tmp.From_To.str.split("_",expand=True)

# Question 3 
# capitalisation of the city names in df_tmp
print(df_tmp)
df_tmp.From = df_tmp.From.str.capitalize()
df_tmp.To = df_tmp.To.str.capitalize()
df_tmp.From_To = df_tmp.From_To.str.capitalize()
print('-'*80)
print(df_tmp)

# Question 4 
# Delete the From_To column from df and attach the temporary DataFrame from the previous questions
print(df)
df.drop('From_To',axis=1,inplace=True)
print('-'*80)
print(df)
df['From_To'] = df_tmp['From_To']
print('-'*80)
print(df)

# Question 5 
rows = []
transformed_df = df.apply(lambda row: [rows.append([row['Airline'], row['FlightNumber'],nn,row['From_To']]) 
                         for nn in row.RecentDelays], axis=1)
df_new = pd.DataFrame(rows, columns=df.columns)
print("Original DataFrame :  \n")
print(df)
print('*'*80)
print("New DataFrame :  \n")
print(df_new)
print("Original DataFrame :  \n")
print(df)
print('*'*80)
print("New DataFrame :  \n")
print(df_new)
df3 = pd.DataFrame(df['RecentDelays'].values.tolist())
length_cols = df3.shape[1]
col_list = []
col_dict ={}
for i in range(length_cols):
    Key = df3.columns[i]
    #print(key,i)
    Value = "Delay" + str(i+1)
    col_dict[Key] = Value
df3.rename(columns=col_dict,inplace=True)
df[["Delay1","Delay2","Delay3"]] = df3[["Delay1","Delay2","Delay3"]]
print(df)
print('*'*80)
df.drop('RecentDelays',axis=1,inplace=True)
print(df)

10045.0
nan
10055.0
10065.0
nan
10075.0
            From_To  FlightNumber  RecentDelays              Airline  \
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN       10055.0            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis       10075.0          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

       From         To
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn
--------------------------------------------------------------------------------
            From_To  FlightNumber  RecentDelays              Airline  \
0      London_paris       10045.0      [23, 47]               KLM(!)
1      Madrid_milan       10055.0            []    <Air France> (12)
2  London_stockholm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_paris       10075.0          [13]       12. Air France
4   Brussels_london       10085.0      [67, 32]          "Swiss Air"

       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN       10055.0            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis       10075.0          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
--------------------------------------------------------------------------------
   FlightNumber  RecentDelays              Airline
0       10045.0      [23, 47]               KLM(!)
1       10055.0            []    <Air France> (12)
2       10065.0  [24, 43, 87]  (British Airways. )
3       10075.0          [13]       12. Air France
4       10085.0      [67, 32]          "Swiss Air"
--------------------------------------------------------------------------------
   FlightNumber  RecentDelays              Airline           From_To
0       10045.0      [23, 47]               KLM(!)      London_paris
1       10055.0            []    <Air France> (12)      Madrid_milan
2       10065.0  [24, 43, 87]  (British Airways. )  London_stockholm
3       10075.0          [13]       12. Air France    Budapest_paris
4       10085.0      [67, 32]          "Swiss Air"   Brussels_london
Original DataFrame :

   FlightNumber  RecentDelays              Airline           From_To
0       10045.0      [23, 47]               KLM(!)      London_paris
1       10055.0            []    <Air France> (12)      Madrid_milan
2       10065.0  [24, 43, 87]  (British Airways. )  London_stockholm
3       10075.0          [13]       12. Air France    Budapest_paris
4       10085.0      [67, 32]          "Swiss Air"   Brussels_london
********************************************************************************
New DataFrame :

          FlightNumber  RecentDelays  Airline           From_To
0               KLM(!)       10045.0       23      London_paris
1               KLM(!)       10045.0       47      London_paris
2  (British Airways. )       10065.0       24  London_stockholm
3  (British Airways. )       10065.0       43  London_stockholm
4  (British Airways. )       10065.0       87  London_stockholm
5       12. Air France       10075.0       13    Budapest_paris
6          "Swiss Air"       10085.0       67   Brussels_london
7          "Swiss Air"       10085.0       32   Brussels_london
Original DataFrame :

   FlightNumber  RecentDelays              Airline           From_To
0       10045.0      [23, 47]               KLM(!)      London_paris
1       10055.0            []    <Air France> (12)      Madrid_milan
2       10065.0  [24, 43, 87]  (British Airways. )  London_stockholm
3       10075.0          [13]       12. Air France    Budapest_paris
4       10085.0      [67, 32]          "Swiss Air"   Brussels_london
********************************************************************************
New DataFrame :

          FlightNumber  RecentDelays  Airline           From_To
0               KLM(!)       10045.0       23      London_paris
1               KLM(!)       10045.0       47      London_paris
2  (British Airways. )       10065.0       24  London_stockholm
3  (British Airways. )       10065.0       43  London_stockholm
4  (British Airways. )       10065.0       87  London_stockholm
5       12. Air France       10075.0       13    Budapest_paris
6          "Swiss Air"       10085.0       67   Brussels_london
7          "Swiss Air"       10085.0       32   Brussels_london
   FlightNumber  RecentDelays              Airline           From_To  Delay1  \
0       10045.0      [23, 47]               KLM(!)      London_paris    23.0
1       10055.0            []    <Air France> (12)      Madrid_milan     NaN
2       10065.0  [24, 43, 87]  (British Airways. )  London_stockholm    24.0
3       10075.0          [13]       12. Air France    Budapest_paris    13.0
4       10085.0      [67, 32]          "Swiss Air"   Brussels_london    67.0

   Delay2  Delay3
0    47.0     NaN
1     NaN     NaN
2    43.0    87.0
3     NaN     NaN
4    32.0     NaN
********************************************************************************
   FlightNumber              Airline           From_To  Delay1  Delay2  Delay3
0       10045.0               KLM(!)      London_paris    23.0    47.0     NaN
1       10055.0    <Air France> (12)      Madrid_milan     NaN     NaN     NaN
2       10065.0  (British Airways. )  London_stockholm    24.0    43.0    87.0
3       10075.0       12. Air France    Budapest_paris    13.0     NaN     NaN
4       10085.0          "Swiss Air"   Brussels_london    67.0    32.0     NaN